### ISSUE TITLE
HA-group module does not support checkmode

### ISSUE THREAD

**Issue by robertattenberger** [ansible-collections/netapp.storagegrid#15]
##### SUMMARY
Calls of the HA-group module are skipped when running them in check-mode.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
netapp.storagegrid.na_sg_grid_ha_group module

##### ANSIBLE VERSION
```paste below
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['{{ MY_HOME_DIR }}/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = {{ MY_HOME_DIR }}/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# /usr/lib/python3.8/site-packages/ansible_collections
Collection         Version
------------------ -------
netapp.storagegrid 21.16.0
```
But collection Version 21.11.1 is also present on the system and configured to use.

##### CONFIGURATION
```paste below
```
no output

##### OS / ENVIRONMENT
Red Hat Enterprise Linux release 8.6 (Ootpa)

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  gather_facts: false
  vars:
    grid_fqdn: mygrid.company.com
    grid_username: root
    grid_password: ********
  tasks:
    - name: Grid authorization token holen
      uri:
        url: "https://{{ grid_fqdn }}/api/v3/authorize"
        method: POST
        body: {
          "username": "{{ grid_username }}",
          "password": "{{ grid_password }}",
          "cookie": false,
          "csrfToken": false
        }
        body_format: json
        validate_certs: false
      register: _grid_auth_token
      check_mode: false
      no_log: true
    - name: Manage HA-Groups
      netapp.storagegrid.na_sg_grid_ha_group:
        api_url: "https://{{ grid_fqdn }}"
        auth_token: "{{ _grid_auth_token.json.data }}"
        gateway_cidr: "192.168.2.1/24"
        interfaces:
          - interface: eth2
            node: node1
        name: myhagroup
        virtual_ips:
          - 192.168.2.10
        validate_certs: false
    - name: Grid authorization token ungeueltig machen
      uri:
        url: "https://{{ grid_fqdn }}/api/v3/authorize"
        method: DELETE
        headers:
          X-Csrf-Token: "{{ _grid_auth_token.json.data }}"
        status_code: 204
        validate_certs: false
      check_mode: false
      no_log: true
...

ansible-playbook playbooks/test.yml --check -vvvv
```

##### EXPECTED RESULTS
For the second task output "ok" or "changed" depending if the HA-group already exists with the mentioned settings or not.

##### ACTUAL RESULTS
```paste below
ansible-playbook [core 2.12.2]
  config file = {{ MY_HOME_DIR }}/storage_ansible/ansible.cfg
  configured module search path = ['{{ MY_HOME_DIR }}/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = {{ MY_HOME_DIR }}/storage_ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True
Using {{ MY_HOME_DIR }}/storage_ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing {{ MY_HOME_DIR }}/storage_ansible/inventories/inventory.yml as it did not pass its verify_file() method
script declined parsing {{ MY_HOME_DIR }}/storage_ansible/inventories/inventory.yml as it did not pass its verify_file() method
Parsed {{ MY_HOME_DIR }}/storage_ansible/inventories/inventory.yml inventory source with yaml plugin
Loading collection netapp.storagegrid from {{ MY_HOME_DIR }}/storage_ansible/collections/ansible_collections/netapp/storagegrid
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading collection community.general from {{ MY_HOME_DIR }}/storage_ansible/collections/ansible_collections/community/general
redirecting (type: callback) ansible.builtin.yaml to community.general.yaml
Loading callback plugin community.general.yaml of type stdout, v2.0 from {{ MY_HOME_DIR }}/storage_ansible/collections/ansible_collections/community/general/plugins/callback/yaml.py
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test.yml *****************************************************************************************************
Positional arguments: playbooks/test.yml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
check: True
inventory: ('{{ MY_HOME_DIR }}/storage_ansible/inventories/inventory.yml',)
forks: 5
1 plays in playbooks/test.yml

PLAY [localhost] *******************************************************************************************************
META: ran handlers

TASK [Grid authorization token holen] **********************************************************************************
task path: {{ MY_HOME_DIR }}/storage_ansible/playbooks/test.yml:9
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: {{ MY_LOGIN_NAME }}
<127.0.0.1> EXEC /bin/sh -c 'echo ~{{ MY_LOGIN_NAME }} && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo {{ MY_HOME_DIR }}/.ansible/tmp `"&& mkdir "` echo {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681153.3082294-2081575-225046606505832 `" && echo ansible-tmp-1668681153.3082294-2081575-225046606505832="` echo {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681153.3082294-2081575-225046606505832 `" ) && sleep 0'
Using module file /usr/lib/python3.8/site-packages/ansible/modules/uri.py
<127.0.0.1> PUT {{ MY_HOME_DIR }}/.ansible/tmp/ansible-local-2081570eqlboveg/tmpaj846t97 TO {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681153.3082294-2081575-225046606505832/AnsiballZ_uri.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681153.3082294-2081575-225046606505832/ {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681153.3082294-2081575-225046606505832/AnsiballZ_uri.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.8 {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681153.3082294-2081575-225046606505832/AnsiballZ_uri.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681153.3082294-2081575-225046606505832/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => changed=false
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'

TASK [Manage HA-Groups] ************************************************************************************************
task path: {{ MY_HOME_DIR }}/storage_ansible/playbooks/test.yml:24
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: {{ MY_LOGIN_NAME }}
<127.0.0.1> EXEC /bin/sh -c 'echo ~{{ MY_LOGIN_NAME }} && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo {{ MY_HOME_DIR }}/.ansible/tmp `"&& mkdir "` echo {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.1492493-2081591-262145993509719 `" && echo ansible-tmp-1668681154.1492493-2081591-262145993509719="` echo {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.1492493-2081591-262145993509719 `" ) && sleep 0'
Using module file {{ MY_HOME_DIR }}/storage_ansible/collections/ansible_collections/netapp/storagegrid/plugins/modules/na_sg_grid_ha_group.py
<127.0.0.1> PUT {{ MY_HOME_DIR }}/.ansible/tmp/ansible-local-2081570eqlboveg/tmpqy7eymyg TO {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.1492493-2081591-262145993509719/AnsiballZ_na_sg_grid_ha_group.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.1492493-2081591-262145993509719/ {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.1492493-2081591-262145993509719/AnsiballZ_na_sg_grid_ha_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.8 {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.1492493-2081591-262145993509719/AnsiballZ_na_sg_grid_ha_group.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.1492493-2081591-262145993509719/ > /dev/null 2>&1 && sleep 0'
skipping: [localhost] => changed=false
  invocation:
    module_args:
      api_url: https://mygrid.company.com
      auth_token: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
      description: null
      gateway_cidr: 192.168.2.1/24
      ha_group_id: null
      interfaces:
      - interface: eth2
        node: node1
      name: myhagroup
      state: present
      validate_certs: false
      virtual_ips:
      - 192.168.2.10
  msg: remote module (netapp.storagegrid.na_sg_grid_ha_group) does not support check mode

TASK [Grid authorization token ungeueltig machen] **********************************************************************
task path: {{ MY_HOME_DIR }}/storage_ansible/playbooks/test.yml:36
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: {{ MY_LOGIN_NAME }}
<127.0.0.1> EXEC /bin/sh -c 'echo ~{{ MY_LOGIN_NAME }} && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo {{ MY_HOME_DIR }}/.ansible/tmp `"&& mkdir "` echo {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.8389733-2081607-53893666566677 `" && echo ansible-tmp-1668681154.8389733-2081607-53893666566677="` echo {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.8389733-2081607-53893666566677 `" ) && sleep 0'
Using module file /usr/lib/python3.8/site-packages/ansible/modules/uri.py
<127.0.0.1> PUT {{ MY_HOME_DIR }}/.ansible/tmp/ansible-local-2081570eqlboveg/tmpjnsujv80 TO {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.8389733-2081607-53893666566677/AnsiballZ_uri.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.8389733-2081607-53893666566677/ {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.8389733-2081607-53893666566677/AnsiballZ_uri.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3.8 {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.8389733-2081607-53893666566677/AnsiballZ_uri.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r {{ MY_HOME_DIR }}/.ansible/tmp/ansible-tmp-1668681154.8389733-2081607-53893666566677/ > /dev/null 2>&1 && sleep 0'
ok: [localhost] => changed=false
  censored: 'the output has been hidden due to the fact that ''no_log: true'' was specified for this result'
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```
